### ISSUE TITLE
samp_function: should we also report a metric for the phylogenetic signal/correlation in the output?

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiC#16]
Many people might also be interested in seeing if and how the parameter for phylogenetic signal will be affected by subsampling. In the case of pgls that would be lambda I suppose, and for logistic regression the phylogenetic correlation parameter alpha should contain similar information. I have updated the code of samp_phyloglm to report both alpha.0 and the alpha for all model runs, so people can analyse these further if they want. But, if you don't think this is wise, do remove again. Most important is we are consistent and do this in all samp_functions or in none, I guess.  For now this has broken plotting the output of samp_phyloglm to sensi_plot, but that can surely be solved if we want this.

**Comment by paternogbc** [comment]
Yes I agree. We should report lambda values for pgls to be consistent. I will update samp_gls very soon. 
This will also break the sensi_plot output, but we can fix this problem later, after all functions are finished.
