### ISSUE TITLE
samp_function: should we also report p-values for the intercept in the output?

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiC#17]
Similar to my previous question: we now only give the p-values for beta in the output. This is what most people will be interested in, but people might also want to know how stable the intercept is (which is already in the output), as well as how that p-value is. I have implemented this in samp_phyloglm for now, but can easily cut.

**Comment by paternogbc** [comment]
Yes, lets report p-values for intercept and beta in the output. 
Thanks!
